# Generated by Django 4.0.3 on 2023-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_is_canceled_appointment_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='vin',
            new_name='import_vin',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
