# Generated by Django 4.0.3 on 2023-03-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_vin_automobilevo_import_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
    ]
